### ISSUE TITLE
yPropName

### ISSUE THREAD

**Issue by andresilvasantos** [Bee-Cave-Games/spine_export#4]
Thank you for your work.

When exporting I got an error complaining that yPropValue is undefined @ 1816.
Changing the variable name at line 1814 from xPropValue to yPropValue fixes this problem.

**Comment by NimaiMalle** [comment]
Wow, thank you!
Yes, looks like the variable declaration was incorrect.  It should be:
`      var yPropName`

inside that second `if` statement of `combineXY`.  I will commit that change.
